name1 = input("Enter a proper noun(person's name): ")
adj1 = input("Enter an adjective: ")
color1 = input("Enter a color: ")
animal1 = input("Enter an animal: ")
place1 = input("Enter a place/location: ")
adj2 = input("Enter an adjective: ")
mag1 = input("Enter a magical creature(plural): ")
adj3 = input("Enter an adjective: ")
mag2 = input("Enter a magical creature(plural): ")
room1 = input("Enter a room in a house: ")
noun1 = input("Enter a noun: ")
noun2 = input("Enter a noun: ")
noun3 = input("Enter a noun: ")
adj4 = input("Enter an adjective: ")
noun4 = input("Enter a noun(plural): ")
num1 = input("Enter a number: ")
time1 = input("Enter a measure of time: ")
verb1 = input("Enver a verb(ending in ing): ")
adj5 = input("Enter an adjective: ")
noun5 = input("Enter a noun: ")
print("Dear " + name1 + ",")
print("I am writing to you from a(n) " + adj1 + " castle in an enchanted forest. I found myself here one day after going for a ride on a(n) " + color1 + " " + animal1 + " in " + place1 + ". There are " + adj2 + " " + mag1 + " and " + adj3 + " " + mag2 + " here! In the " + room1 + " there is a pool full of " + noun1 + ". I fall asleep each night on a(n) " + noun2 + " of " + noun3 + " and dream of " + adj4 + " " + noun4 + ". It feels as though I have lived here for " + num1 + " " + time1 + ". I hope one day you can visit, although the only way to get here now is " + verb1 + " on a(n) " + adj5 + " " + noun5 + "!!")



